USE [Company]
GO
/****** Object:  StoredProcedure [dbo].[ADD_GST_COLUMNS]    Script Date: 17-07-2017 14:48:25 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ADD_GST_COLUMNS]
AS
BEGIN

DECLARE @BILLSQLSTMT NVARCHAR(MAX);
DECLARE @BILLTABLENAME NVARCHAR(50);
DECLARE @BILLITEMSTABLENAME NVARCHAR(50);
DECLARE CBILLS CURSOR READ_ONLY
FOR
SELECT BILLTABLE,BILLITEMSTABLE FROM OLDBILLTABLES;

SET @BILLTABLENAME = 'BILLS';
SET @BILLITEMSTABLENAME = 'BILLITEMS';
SET @BILLSQLSTMT = '';

OPEN CBILLS
FETCH NEXT FROM CBILLS INTO @BILLTABLENAME,@BILLITEMSTABLENAME
WHILE @@FETCH_STATUS = 0
BEGIN
	SET @BILLSQLSTMT = 'alter table ' + @BILLTABLENAME + 'add SGST float;';
	EXECUTE sp_executesql @BILLSQLSTMT;
	SET @BILLSQLSTMT = 'alter table ' + @BILLTABLENAME + 'add CGST float;';
	EXECUTE sp_executesql @BILLSQLSTMT;
	SET @BILLSQLSTMT = 'alter table ' + @BILLTABLENAME + 'add IGST float;';
	EXECUTE sp_executesql @BILLSQLSTMT;
	SET @BILLSQLSTMT = 'alter table ' + @BILLTABLENAME + 'add TOTALAFTERTAX float;';
	EXECUTE sp_executesql @BILLSQLSTMT;
	SET @BILLSQLSTMT = 'alter table ' + @BILLITEMSTABLENAME + 'add HSN nvarchar(100);';
	EXECUTE sp_executesql @BILLSQLSTMT;
	FETCH NEXT FROM CBILLS INTO @BILLTABLENAME,@BILLITEMSTABLENAME
END
CLOSE CBILLS
DEALLOCATE CBILLS

END
