USE [Company]
GO
/****** Object:  StoredProcedure [dbo].[ADD_GST_COLUMNS]    Script Date: 21-07-2017 19:00:24 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ADD_PARTICULAR_COLUMNS]
AS
BEGIN

DECLARE @BILLSQLSTMT NVARCHAR(MAX);
DECLARE @BILLTABLENAME NVARCHAR(50);
DECLARE CBILLS CURSOR READ_ONLY
FOR
SELECT BILLTABLE FROM OLDBILLTABLES;

SET @BILLTABLENAME = 'BILLS';
SET @BILLSQLSTMT = '';

OPEN CBILLS
FETCH NEXT FROM CBILLS INTO @BILLTABLENAME
WHILE @@FETCH_STATUS = 0
BEGIN
	SET @BILLSQLSTMT = 'alter table ' + @BILLTABLENAME + ' add PARTICULARS nvarchar(1000) NULL;';
	EXECUTE sp_executesql @BILLSQLSTMT;
	FETCH NEXT FROM CBILLS INTO @BILLTABLENAME
END
CLOSE CBILLS
DEALLOCATE CBILLS
-- add to bills table
SET @BILLSQLSTMT = 'alter table bills add PARTICULARS nvarchar(1000) NULL;';
EXECUTE sp_executesql @BILLSQLSTMT;
END
