USE [Company]
GO
/****** Object:  StoredProcedure [dbo].[ADD_GST_COLUMNS]    Script Date: 07-08-2017 06:53:54 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ADD_TOTALBEFORETAX_COLUMN]
AS
BEGIN

DECLARE @BILLSQLSTMT NVARCHAR(MAX);
DECLARE @BILLTABLENAME NVARCHAR(50);
DECLARE CBILLS CURSOR READ_ONLY
FOR
SELECT BILLTABLE FROM OLDBILLTABLES;

SET @BILLTABLENAME = 'BILLS';
SET @BILLSQLSTMT = '';

OPEN CBILLS
FETCH NEXT FROM CBILLS INTO @BILLTABLENAME
WHILE @@FETCH_STATUS = 0
BEGIN
	SET @BILLSQLSTMT = 'alter table ' + @BILLTABLENAME + 'add TOTALBEFORETAX float;';
	EXECUTE sp_executesql @BILLSQLSTMT;
	FETCH NEXT FROM CBILLS INTO @BILLTABLENAME
END
CLOSE CBILLS
DEALLOCATE CBILLS

SET @BILLSQLSTMT = 'alter table bills add TOTALBEFORETAX float;';
EXECUTE sp_executesql @BILLSQLSTMT;

END
