USE [Company]
GO
/****** Object:  UserDefinedFunction [dbo].[GET_DDENTRYBILLQUERY]    Script Date: 11-08-2017 21:52:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Mohan
-- Create date: 22 Dec 2007
-- Description:	get sql statement for bills table
-- =============================================
ALTER FUNCTION [dbo].[GET_DDENTRYBILLQUERY]
(@ADDRESS varchar(50), @FROMDATE varchar(50), @TODATE varchar(50), @BILLTABLENAME varchar(50),@BILLPAYMENTSTABLENAME varchar(30))--@AGENT varchar(50),
RETURNS NVARCHAR(4000)
AS
BEGIN
	DECLARE @WHERESQLSTMT NVARCHAR(4000);
	DECLARE @BILLNOSQLSTMT NVARCHAR(4000);
	DECLARE @BILLSSQLSTMT NVARCHAR(4000);
	
	SET @BILLNOSQLSTMT = 'SELECT B.BILLNO FROM ' + @BILLTABLENAME + ' AS B ';
	SET @BILLSSQLSTMT = 'SELECT B.BILLNO, B.ADDRESS, B.BILLDATE, P.CITY,P.NAME AS PARTY, B.AGENT, ROUND(B.TOTALWOCD,0) AS TOTALWOCD, B.TOTALBEFORETAX,B.IGST,B.TOTALAFTERTAX, B.BALANCE,''' + @BILLPAYMENTSTABLENAME + ''' AS TABLENAME 
					 FROM ' + @BILLTABLENAME + ' AS B INNER JOIN PARTIES AS P ON P.ID = B.PARTYID'; 
	SET @WHERESQLSTMT = ' WHERE     (B.ADDRESS = ''' + @ADDRESS + ''')';
	--IF (@AGENT != NULL AND @AGENT != '')
	--	SET @WHERESQLSTMT = @WHERESQLSTMT + ' AND (B.AGENT = ''' + @AGENT + ''')';
	IF (@FROMDATE IS NOT NULL AND @FROMDATE != '')
		SET @WHERESQLSTMT = @WHERESQLSTMT + ' AND B.BILLDATE >= (CONVERT(datetime, ''' + @FROMDATE + ''', 103))';
	IF (@TODATE IS NOT NULL AND @TODATE != '')
		SET @WHERESQLSTMT = @WHERESQLSTMT + ' AND B.BILLDATE <= (CONVERT(datetime, ''' + @TODATE + ''', 103))';
	SET @BILLSSQLSTMT = @BILLSSQLSTMT + @WHERESQLSTMT ;
	SET @BILLNOSQLSTMT = @BILLNOSQLSTMT + @WHERESQLSTMT;
	RETURN @BILLSSQLSTMT;
END

